// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD29Hh2-UUmO3XeWsMcbFmzXcBaTUHKtsg',
    appId: '1:852603417654:web:c1f0302228af7bbcf29497',
    messagingSenderId: '852603417654',
    projectId: 'mcqqiuzapp',
    authDomain: 'mcqqiuzapp.firebaseapp.com',
    storageBucket: 'mcqqiuzapp.firebasestorage.app',
    measurementId: 'G-07BMSRBCNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd_2wKUZMCHjewgUt4knzvUfcwe--NR6o',
    appId: '1:852603417654:android:ad67ba55c72e7368f29497',
    messagingSenderId: '852603417654',
    projectId: 'mcqqiuzapp',
    storageBucket: 'mcqqiuzapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHrGpIFbFs31uSc6o7xY9IHu8X8zHuw5E',
    appId: '1:852603417654:ios:0309e24cf9f9da05f29497',
    messagingSenderId: '852603417654',
    projectId: 'mcqqiuzapp',
    storageBucket: 'mcqqiuzapp.firebasestorage.app',
    iosBundleId: 'com.example.mcqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHrGpIFbFs31uSc6o7xY9IHu8X8zHuw5E',
    appId: '1:852603417654:ios:0309e24cf9f9da05f29497',
    messagingSenderId: '852603417654',
    projectId: 'mcqqiuzapp',
    storageBucket: 'mcqqiuzapp.firebasestorage.app',
    iosBundleId: 'com.example.mcqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD29Hh2-UUmO3XeWsMcbFmzXcBaTUHKtsg',
    appId: '1:852603417654:web:2142407efd7363cbf29497',
    messagingSenderId: '852603417654',
    projectId: 'mcqqiuzapp',
    authDomain: 'mcqqiuzapp.firebaseapp.com',
    storageBucket: 'mcqqiuzapp.firebasestorage.app',
    measurementId: 'G-LZ64271C7J',
  );
}
